config:
  validation: true
  warningsAsErrors: true

processors:
  active: true

console-reports:
  active: true
  exclude:
    - ProjectStatisticsReport

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
      - Preview
      - Test
      - BeforeTest
      - AfterTest

complexity:
  active: true
  LongMethod:
    active: true
    allowedLines: 80
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 10
    ignoreDefaultParameters: true
    ignoreDataClasses: true
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 20
  NestedBlockDepth:
    active: true
    allowedDepth: 4
  LargeClass:
    active: true
    allowedLines: 600

style:
  active: true
  ReturnCount:
    active: true
    max: 4
  ThrowsCount:
    active: true
    max: 2
